spring:
  application:
    name: what-has-changed
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
  shell:
    interactive:
      enabled: true
debug: true
application:
  ranking-url: ${STEAM_APP_RANKING_SOURCE_URL}
